### ISSUE TITLE
Cannot import name 'Actor' from 'xbmc'

### ISSUE THREAD

**Issue by t0mtee** [pkscout/metadata.tvshows.themoviedb.org.python#101]
```
2023-02-04 23:04:50.121 T:10100   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://metadata.tvshows.themoviedb.org.python/?action=find&pathSettings=%7b%22cat_landscape%22%3atrue%2c%22certprefix%22%3a%22Rated%20%22%2c%22enab_trailer%22%3atrue%2c%22enable_fanarttv%22%3atrue%2c%22fanarttv_clientkey%22%3a%22%22%2c%22imdbanyway%22%3atrue%2c%22keeporiginaltitle%22%3afalse%2c%22language%22%3a%22en-US%22%2c%22lastUpdated%22%3a%220%22%2c%22originalUrl%22%3a%22%22%2c%22players_opt%22%3a%22YouTube%22%2c%22previewUrl%22%3a%22%22%2c%22ratings%22%3a%22TMDb%22%2c%22studio_country%22%3atrue%2c%22tmdbanyway%22%3afalse%2c%22tmdbcertcountry%22%3a%22gb%22%2c%22traktanyway%22%3afalse%2c%22usecertprefix%22%3atrue%2c%22verboselog%22%3afalse%7d&title=Utopia&year=2013
2023-02-04 23:04:50.122 T:23232    INFO <general>: initializing python engine.
2023-02-04 23:04:50.289 T:23232   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'Actor' from 'xbmc' (unknown location)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\x\AppData\Roaming\Kodi\addons\metadata.tvshows.themoviedb.org.python\main.py", line 27, in <module>
                                                       from libs.actions import router
                                                     File "C:\Users\x\AppData\Roaming\Kodi\addons\metadata.tvshows.themoviedb.org.python\libs\actions.py", line 29, in <module>
                                                       from . import tmdb, data_utils
                                                     File "C:\Users\x\AppData\Roaming\Kodi\addons\metadata.tvshows.themoviedb.org.python\libs\tmdb.py", line 26, in <module>
                                                       from . import cache, data_utils, api_utils, settings, imdbratings, traktratings
                                                     File "C:\Users\x\AppData\Roaming\Kodi\addons\metadata.tvshows.themoviedb.org.python\libs\data_utils.py", line 26, in <module>
                                                       from xbmc import Actor, VideoStreamDetail
                                                   ImportError: cannot import name 'Actor' from 'xbmc' (unknown location)
                                                   -->End of Python script error report<--
                                                   
2023-02-04 23:04:50.519 T:23232    INFO <general>: Python interpreter stopped
```

Happens whenever I try to scrape using this addon. Kodi 19.5, Windows 10, connected to a MariaDB database.

**Comment by KarellenX** [comment]
Need the full log.

**Comment by t0mtee** [comment]
[kodi.log](https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/files/10610616/kodi.log)
This is a normal log, can get a debug if you want

**Comment by KarellenX** [comment]
Always a debug log.

**Comment by t0mtee** [comment]
[kodi.log](https://github.com/xbmc/metadata.tvshows.themoviedb.org.python/files/10612019/kodi.log)

**Comment by KarellenX** [comment]
You seem to be using the wrong version of scraper.
You somehow are using an older Nexus version of the scraper but you have Matrix installed.
The latest version of the Matrix scraper is v1.4.18... 
https://mirrors.kodi.tv/addons/matrix/metadata.tvshows.themoviedb.org.python/
Install the correct version scraper and check if the problem persists.

**Comment by t0mtee** [comment]
Strange, will install.

**Comment by t0mtee** [comment]
Works great now, thanks and sorry the easy solution that I didn't see
