### ISSUE TITLE
Scan / Scrap is broken in 1.70 (ok in 1.65)

### ISSUE THREAD

**Issue by Gates33** [pkscout/metadata.tvshows.themoviedb.org.python#121]
Hi,

My scan are broken with version 1.70
When I switched back to 1.65, it's OK

```
2024-11-07 20:53:24.026 T:601141   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'TMDB_CLOWNCAR' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/main.py", line 27, in <module>
                                                       from libs.actions import router
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/actions.py", line 30, in <module>
                                                       from . import tmdb, data_utils
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/tmdb.py", line 26, in <module>
                                                       from . import cache, data_utils, api_utils, settings, imdbratings, traktratings
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/data_utils.py", line 30, in <module>
                                                       from . import settings, api_utils
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/settings.py", line 107, in <module>
                                                       IMAGEROOTURL, PREVIEWROOTURL = _load_base_urls()
                                                                                      ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/settings.py", line 43, in _load_base_urls
                                                       conf = _get_configuration()
                                                              ^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/settings.py", line 34, in _get_configuration
                                                       return api_utils.load_info('https://api.themoviedb.org/3/configuration', params={'api_key': TMDB_CLOWNCAR}, verboselog=VERBOSELOG)
                                                                                                                                                   ^^^^^^^^^^^^^
                                                   NameError: name 'TMDB_CLOWNCAR' is not defined
                                                   -->End of Python script error report<--
                                                   
2024-11-07 20:53:24.064 T:601140   error <general>: GetDirectory - Error getting plugin://metadata.tvshows.themoviedb.org.python/?action=find&pathSettings=%7b%22cat_landscape%22%3atrue%2c%22certprefix%22%3a%22Rated%20%22%2c%22enab_trailer%22%3atrue%2c%22enable_fanarttv%22%3atrue%2c%22fanarttv_clientkey%22%3a%22723205cce12b6227e064cc55732c9d24%22%2c%22imdbanyway%22%3afalse%2c%22keeporiginaltitle%22%3afalse%2c%22keywordsastags%22%3atrue%2c%22language%22%3a%22fr-FR%22%2c%22languageDetails%22%3a%22en-US%22%2c%22languageImages%22%3a%22en-US%22%2c%22lastUpdated%22%3a%221694303969.565935%22%2c%22originalUrl%22%3a%22https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%22%2c%22players_opt%22%3a%22Tubed%22%2c%22previewUrl%22%3a%22https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw780%22%2c%22ratings%22%3a%22TMDb%22%2c%22studio_country%22%3afalse%2c%22tmdbanyway%22%3atrue%2c%22tmdbcertcountry%22%3a%22us%22%2c%22traktanyway%22%3afalse%2c%22usecertprefix%22%3atrue%2c%22usedifferentlangforimages%22%3afalse%2c%22verboselog%22%3afalse%7d&title=Bluey
2024-11-07 20:53:24.186 T:601142   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'NameError'>
                                                   Error Contents: name 'TMDB_CLOWNCAR' is not defined
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/main.py", line 27, in <module>
                                                       from libs.actions import router
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/actions.py", line 30, in <module>
                                                       from . import tmdb, data_utils
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/tmdb.py", line 26, in <module>
                                                       from . import cache, data_utils, api_utils, settings, imdbratings, traktratings
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/data_utils.py", line 30, in <module>
                                                       from . import settings, api_utils
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/settings.py", line 107, in <module>
                                                       IMAGEROOTURL, PREVIEWROOTURL = _load_base_urls()
                                                                                      ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/settings.py", line 43, in _load_base_urls
                                                       conf = _get_configuration()
                                                              ^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/libs/settings.py", line 34, in _get_configuration
                                                       return api_utils.load_info('https://api.themoviedb.org/3/configuration', params={'api_key': TMDB_CLOWNCAR}, verboselog=VERBOSELOG)
                                                                                                                                                   ^^^^^^^^^^^^^
                                                   NameError: name 'TMDB_CLOWNCAR' is not defined
                                                   -->End of Python script error report<--
                                                   
2024-11-07 20:53:24.230 T:601140   error <general>: GetDirectory - Error getting plugin://metadata.tvshows.themoviedb.org.python/?action=find&pathSettings=%7b%22cat_landscape%22%3atrue%2c%22certprefix%22%3a%22Rated%20%22%2c%22enab_trailer%22%3atrue%2c%22enable_fanarttv%22%3atrue%2c%22fanarttv_clientkey%22%3a%22723205cce12b6227e064cc55732c9d24%22%2c%22imdbanyway%22%3afalse%2c%22keeporiginaltitle%22%3afalse%2c%22keywordsastags%22%3atrue%2c%22language%22%3a%22fr-FR%22%2c%22languageDetails%22%3a%22en-US%22%2c%22languageImages%22%3a%22en-US%22%2c%22lastUpdated%22%3a%221694303969.565935%22%2c%22originalUrl%22%3a%22https%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%22%2c%22players_opt%22%3a%22Tubed%22%2c%22previewUrl%22%3a%22https%3a%2f%2fimage.tmdb.org%2ft%2fp%2fw780%22%2c%22ratings%22%3a%22TMDb%22%2c%22studio_country%22%3afalse%2c%22tmdbanyway%22%3atrue%2c%22tmdbcertcountry%22%3a%22us%22%2c%22traktanyway%22%3afalse%2c%22usecertprefix%22%3atrue%2c%22usedifferentlangforimages%22%3afalse%2c%22verboselog%22%3afalse%7d&title=Bluey
2024-11-07 20:53:24.252 T:1147     info <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
```

**Comment by KarellenX** [comment]
Already fixed... https://github.com/xbmc/repo-scrapers/pull/546
and... https://forum.kodi.tv/showthread.php?tid=379378&pid=3215121#pid3215121
