### ISSUE TITLE
KeyError in lib.data_utils._set_cast(cast_info, list_item) on the Matrix branch

### ISSUE THREAD

**Issue by Animajosser** [pkscout/metadata.tvshows.themoviedb.org.python#23]
Reproduce by trying to add a TV Show with the name: "My Life as A Teenage Robot"

It looks like the keys for characters for quest stars and normal cast are different ("character" for cast and "character_name" for guest). See: https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-credits

The stacktrace:
Error Type: <class 'KeyError'>
Error Contents: 'character'
Traceback (most recent call last):
  File "/usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/main.py", line 32, in <module>
    router(sys.argv[2][1:])
  File "/usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/libs/actions.py", line 195, in router
    get_episode_details(params['url'])
  File "/usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/libs/actions.py", line 151, in get_episode_details
    list_item = data_utils.add_episode_info(list_item, episode_info, full_info=True)
  File "/usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/libs/data_utils.py", line 283, in add_episode_info
    list_item = _set_cast(episode_info['credits']['guest_stars'], list_item)
  File "/usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/libs/data_utils.py", line 77, in _set_cast
    'role': item['character'],
  KeyError: 'character'

The input:
cast_info = [{'adult': False,
                     'character_name': '',
                     'credit_id': '525343b619c29579400b247e',
                     'gender': 0,
                     'id': 64951,
                     'known_for_department': 'Acting',
                     'name': 'Neil Ross',
                     'order': 0,
                     'original_name': 'Neil Ross',
                     'popularity': 2.588,
                     'profile_path': '/pNgkQKw5k6z9kscDnOAwstcmNnt.jpg'}]

**Comment by pkscout** [comment]
We are aware of the error and working on a fix right now.

**Comment by pkscout** [comment]
Fixed with d030401. The main repo should be updated in the next day or so. If you need the fix immediately, you can download the zip of the code from the Matrix branch.
